### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by sabrehagen** [lemourin/cloudstorage-js#1]
Hello! A clean build of this app does not succeed. Am I missing a dependency?

```sh
git clone https://github.com/lemourin/cloudstorage-js
cd cloudstorage-js
npm install
npm run build
```

```sh

> cloudstorage-js@ build:all /home/jackson/repositories/tmp/cloudstorage-js
> npm run build && npm run build:contrib && npm run build:emscripten


> cloudstorage-js@ build /home/jackson/repositories/tmp/cloudstorage-js
> webpack --mode=development

/home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack-cli/bin/cli.js:89
				throw err;
				^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/home/jackson/repositories/tmp/cloudstorage-js/webpack.config.js:48:14)
    at Module._compile (/home/jackson/repositories/tmp/cloudstorage-js/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (/home/jackson/repositories/tmp/cloudstorage-js/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack-cli/bin/utils/convert-argv.js:116:13)
    at requireConfig (/home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack-cli/bin/utils/convert-argv.js:118:6)
    at /home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack-cli/bin/utils/convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack-cli/bin/utils/convert-argv.js:123:15)
    at /home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/jackson/repositories/tmp/cloudstorage-js/node_modules/yargs/yargs.js:567:18)
    at /home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack-cli/bin/cli.js:386:3)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/jackson/repositories/tmp/cloudstorage-js/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cloudstorage-js@ build: `webpack --mode=development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cloudstorage-js@ build script.

```

**Comment by lemourin** [comment]
You need a `.env` file in the source directory with content similiar to this:
```
EMSDK_HOME=/home/lemourin/Projects/emsdk
HOSTNAME=http://localhost:8000
```
* `EMSDK_HOME` points to the directory with `emsdk` checked out and installed from here: https://github.com/emscripten-core/emsdk
* `HOSTNAME` is the url at which the `cloudstorage-js` repo is exposed.

To test the app, run `npm run build:all` and serve the repository with any http server, e.g. with
`python3 -m http.server`.

**Comment by sabrehagen** [comment]
After providing `emsdk` the file `emsdk_set_env.sh` can't be found. I notice it is in the [.gitignore](https://github.com/emscripten-core/emsdk/blob/master/.gitignore#L4). Is this file auto-generated?

```sh
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[react] external "React" 42 bytes {main} [built]
[react-dom] external "ReactDOM" 42 bytes {main} [built]
    + 180 hidden modules

 cloudstorage-js@ build:contrib /home/jackson/repositories/tmp/cloudstorage-js
> . "$(cat .env | grep EMSDK_HOME | sed -E "s/EMSDK_HOME=(.*)/\1/")/emsdk_set_env.sh" && cd contrib && ./bootstrap

sh: 1: .: Can't open /home/jackson/repositories/tmp/cloudstorage-js/emsdk/emsdk_set_env.sh
```

**Comment by lemourin** [comment]
According to https://emscripten.org/docs/getting_started/downloads.html
you should do `./emsdk install latest` and `./emsdk activate latest` after cloning.
Those commands most likely will create the missing script.

**Comment by sabrehagen** [comment]
You'd think they'd put those critical steps in their README. I've created a [Dockerfile](https://github.com/cloud-computer/cloudstorage-js/blob/master/Dockerfile#L14) to run the setup but it still gets the [same error](https://cloud.docker.com/repository/registry-1.docker.io/sabrehagen/cloudstorage-js/builds/3fc21fd3-d4a4-4d94-b848-8983836d16ca); no `emsdk_set_env.sh` exists.

I found [a comment](https://github.com/emscripten-core/emscripten/issues/2918#issuecomment-60129322) saying `emsdk_set_env.sh` is deprecated. Are you using an older version of the SDK?

**Comment by lemourin** [comment]
I updated `package.json` to use `emsdk_env.sh` script.
